apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "hello-world"
  annotations:
    github.com/project-slug: "larisa-sehic/hello-world"
    newrelic.com/dashboard-guid: 'MzEwNTQR8ZGE6NDUwNTEzNQ'
    sonarqube.org/project-key: 'e4_HURmDei0uWWjS3s'
    pagerduty.com/integration-key: 'a36133058d5c91'
    additional-info/stream-lead: 'Jane doe'
    additional-info/engineering-manager: 'John Doe'
    additional-info/tech-lead: 'Unknown'
    additional-info/testing-role-something: 'Something'
    additional-info/sql-database: 'Admin'
    tier-info/tier: '1'
    test/test-info: 'graphql'
spec:
  type: service
  lifecycle: production
  owner: darwin
  system: platform
  dependsOn: 
    - component:default/test-component-backstage
  consumesApis:
    - API:default/external-federation
