apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hello-world
  annotations:
    github.com/project-slug: "larisa-sehic/hello-world"
    additional-info/stream-lead: "John Joe"
    additional-info/engineering-manager: "Jane Doe"
    sonarqube.org/project-key: 'jS3s'
    
spec:
  type: service
  owner: larisa-sehic
  lifecycle: experimental
